coverage:
  ignore:
    - "src/main/java/com/gederin/SpringMongoApplication.java"
    - "src/main/java/com/gederin/model/"
    - "src/test/java/com/gederin/.*"
    - "src/main/java/com/gederin/util/Constants.java"